# Generated by Django 5.2.5 on 2026-03-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_contents_publisher_alter_contents_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='contents',
            name='list_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
