# Generated by Django 5.2.5 on 2026-03-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_price_contents_base_price_contents_list_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_purchase',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_price_at_purchase',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='list_price_at_purchase',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contents',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
